// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY5cZy-RUQrTuZMBi8MRQKZTbr8YRcZ-c',
    appId: '1:197386697750:web:abcdef123456789',
    messagingSenderId: '197386697750',
    projectId: 'core-craft-clothing',
    authDomain: 'core-craft-clothing.firebaseapp.com',
    storageBucket: 'core-craft-clothing.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY5cZy-RUQrTuZMBi8MRQKZTbr8YRcZ-c',
    appId: '1:197386697750:android:b3266e57a91c00d56b4937',
    messagingSenderId: '197386697750',
    projectId: 'core-craft-clothing',
    storageBucket: 'core-craft-clothing.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvQZvQZvQZvQZvQZvQZvQZvQZvQZvQZvQ',
    appId: '1:123456789:ios:abcdef123456789',
    messagingSenderId: '123456789',
    projectId: 'core-craft-ecommerce',
    storageBucket: 'core-craft-ecommerce.appspot.com',
    iosBundleId: 'com.example.coreCraftEcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvQZvQZvQZvQZvQZvQZvQZvQZvQZvQZvQ',
    appId: '1:123456789:ios:abcdef123456789',
    messagingSenderId: '123456789',
    projectId: 'core-craft-ecommerce',
    storageBucket: 'core-craft-ecommerce.appspot.com',
    iosBundleId: 'com.example.coreCraftEcommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvQZvQZvQZvQZvQZvQZvQZvQZvQZvQZvQ',
    appId: '1:123456789:web:abcdef123456789',
    messagingSenderId: '123456789',
    projectId: 'core-craft-ecommerce',
    authDomain: 'core-craft-ecommerce.firebaseapp.com',
    storageBucket: 'core-craft-ecommerce.appspot.com',
    measurementId: 'G-XXXXXXXXXX',
  );
}
